### ISSUE TITLE
0.1.38 doesn't work (webpack5)

### ISSUE THREAD

**Issue by sorteam** [LabEG/first-di#3]
WARNING:
export 'reflection' (imported as 'reflection') was not found in 'first-di' (possible exports: autowired, instance, override, reset, resolve, singleton)

ERROR in ./node_modules/first-di/dist/index.mjs 3:0-45
Module not found: Error: Can't resolve './models/autowired-lifetimes' in '...\node_modules\first-di\dist'
Did you mean 'autowired-lifetimes.js'?
BREAKING CHANGE: The request './models/autowired-lifetimes' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by LabEG** [comment]
Can you create repository that reproduces problem?

In this release code was split into EMS and CommonJS modules. For correct work Node.js in module mode. But webpack still has problems with mjs files. They are solved by configuring webpack.

For example, the config helped us:
`
        {
            test: /\.mjs$/,
            include: /node_modules/,
            type: "javascript/auto"
        }
`

[Issue in webpack repository](https://github.com/webpack/webpack/issues/11467).

**Comment by sorteam** [comment]
> Can you create repository that reproduces problem?
> 
> In this release code was split into EMS and CommonJS modules. For correct work Node.js in module mode. But webpack still has problems with mjs files. They are solved by configuring webpack.
> 
> For example, the config helped us:
> `{ test: /\.mjs$/, include: /node_modules/, type: "javascript/auto" }`
> 
> [Issue in webpack repository](https://github.com/webpack/webpack/issues/11467).

It works, thank you.
