### ISSUE TITLE
Class field decorated with @autowired is undefined

### ISSUE THREAD

**Issue by stronkz** [LabEG/first-di#4]
### Expected behavior

      @autowired()
      private readonly myService!: AService;
  
      private readonly myStr: string;
  
      constructor() {
         this.myStr = "test";
      }
  
      public foo():string {
          return this.myService.getObj();
      }
  
Call of `foo` method returns string 

### Actual behavior

 `this.myService` is undefined insade `foo` method

      @autowired()
      private readonly myService!: AService;
  
      private readonly myStr: string;
  
      constructor() {
         this.myStr = "test";
      }
  
      public foo():string {
          return this.myService.getObj();
          //TypeError: Cannot read properties of undefined
      }

Steps to reproduce behavior:
1. typescript version >=3.7
2. set `useDefineForClassFields: true` in tsconfig.json

**Comment by LabEG** [comment]
useDefineForClassFields - doesn't support decorators right now. Typescript team is aware of this issue.
https://github.com/microsoft/TypeScript/issues/35081

It is necessary to wait for a decision from the Tipscript team. There is a solution because decorators use many well-known libraries.
